 try{
    let a=b;
 }catch(err){
    console.log("Message :"+err);//e and err display type of error
 }
